# This is a Dockerfile of "centos7_base"
FROM akkytech0617/my_centos7:base
LABEL maintainer="akkytech0617@gmail.com"
# install node.js 12.x
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash - \
 && yum -y install nodejs